server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usermanagement
    username: root
    password: root
    
  spring:
      mail:
       host: smtp.gmail.com  
       port: 587
       username: aryadewan123@gmail.com
       password: shivajitheboss
       properties: 
                mail: 
                  smtp: 
                    auth: true 
                    starttls:
                      enable: true
    
   
mvc:
    views:
      prefix: /views/
      suffix: .jsp
      
