server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usermanagement
    username: root
    password: root
    
   
  mvc:
    views:
      prefix: /views/
      suffix: .jsp
      
